"""Add requirement_tags and target_resume_count to positions

Revision ID: 4c437f655beb
Revises: 0009_remove_auto_entry
Create Date: 2026-07-02 00:33:40.249237

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c437f655beb'
down_revision: Union[str, None] = '0009_remove_auto_entry'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ai_tasks', 'created_by',
               existing_type=sa.TEXT(),
               type_=sa.String(length=64),
               existing_nullable=False,
               existing_server_default=sa.text("''::text"))
    op.alter_column('candidate_tracking_events', 'interview_round',
               existing_type=sa.TEXT(),
               type_=sa.String(length=32),
               existing_nullable=False,
               existing_server_default=sa.text("''::text"))
    op.alter_column('candidate_tracking_events', 'screening_result',
               existing_type=sa.TEXT(),
               type_=sa.String(length=32),
               existing_nullable=False,
               existing_server_default=sa.text("''::text"))
    op.alter_column('candidate_tracking_events', 'interview_date',
               existing_type=sa.TEXT(),
               type_=sa.String(length=32),
               existing_nullable=False,
               existing_server_default=sa.text("''::text"))
    op.alter_column('candidate_tracking_events', 'interviewer',
               existing_type=sa.TEXT(),
               type_=sa.String(length=64),
               existing_nullable=False,
               existing_server_default=sa.text("''::text"))
    op.alter_column('candidate_tracking_events', 'interview_location',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=False,
               existing_server_default=sa.text("''::text"))
    op.alter_column('candidate_tracking_events', 'interview_contact',
               existing_type=sa.TEXT(),
               type_=sa.String(length=128),
               existing_nullable=False,
               existing_server_default=sa.text("''::text"))
    op.alter_column('candidate_tracking_events', 'interview_result',
               existing_type=sa.TEXT(),
               type_=sa.String(length=32),
               existing_nullable=False,
               existing_server_default=sa.text("'-'::text"))
    op.alter_column('candidate_tracking_events', 'employment_status',
               existing_type=sa.TEXT(),
               type_=sa.String(length=32),
               existing_nullable=False,
               existing_server_default=sa.text("'待设置'::text"))
    op.alter_column('candidates', 'file_path',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               nullable=True,
               existing_server_default=sa.text("''::text"))
    op.create_index(op.f('ix_candidates_owner_user_id'), 'candidates', ['owner_user_id'], unique=False)
    op.create_index(op.f('ix_companies_owner_user_id'), 'companies', ['owner_user_id'], unique=False)
    op.alter_column('export_records', 'contract_no',
               existing_type=sa.TEXT(),
               type_=sa.String(length=128),
               existing_nullable=False,
               existing_server_default=sa.text("''::text"))
    op.alter_column('export_records', 'project_no',
               existing_type=sa.TEXT(),
               type_=sa.String(length=128),
               existing_nullable=False,
               existing_server_default=sa.text("''::text"))
    op.alter_column('export_records', 'headhunter_position',
               existing_type=sa.TEXT(),
               type_=sa.String(length=128),
               existing_nullable=False,
               existing_server_default=sa.text("''::text"))
    op.add_column('positions', sa.Column('requirement_tags', sa.JSON(), nullable=True))
    op.add_column('positions', sa.Column('target_resume_count', sa.Integer(), nullable=False, server_default='10'))
    op.create_index(op.f('ix_positions_owner_user_id'), 'positions', ['owner_user_id'], unique=False)
    op.create_index(op.f('ix_projects_owner_user_id'), 'projects', ['owner_user_id'], unique=False)
    op.alter_column('salary_records', 'interview_round',
               existing_type=sa.TEXT(),
               type_=sa.String(length=64),
               existing_nullable=False,
               existing_server_default=sa.text("''::text"))
    op.alter_column('salary_records', 'position_name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=False,
               existing_server_default=sa.text("''::text"))
    op.alter_column('salary_records', 'company_name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=False,
               existing_server_default=sa.text("''::text"))
    op.alter_column('salary_records', 'agreed_salary',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=False,
               existing_server_default=sa.text("''::text"))
    op.alter_column('salary_records', 'candidate_accepted',
               existing_type=sa.TEXT(),
               type_=sa.String(length=32),
               existing_nullable=False,
               existing_server_default=sa.text("''::text"))
    op.alter_column('salary_records', 'operator',
               existing_type=sa.TEXT(),
               type_=sa.String(length=64),
               existing_nullable=False,
               existing_server_default=sa.text("''::text"))
    op.create_foreign_key(None, 'salary_records', 'positions', ['position_id'], ['id'])
    op.alter_column('tag_dictionaries', 'object_type',
               existing_type=sa.TEXT(),
               type_=sa.String(length=32),
               existing_nullable=False,
               existing_server_default=sa.text("'candidate'::text"))
    op.alter_column('tag_dictionaries', 'field_key',
               existing_type=sa.TEXT(),
               type_=sa.String(length=64),
               existing_nullable=False,
               existing_server_default=sa.text("''::text"))
    op.alter_column('tag_dictionaries', 'field_label',
               existing_type=sa.TEXT(),
               type_=sa.String(length=128),
               existing_nullable=False,
               existing_server_default=sa.text("''::text"))
    op.alter_column('tag_dictionaries', 'style_key',
               existing_type=sa.TEXT(),
               type_=sa.String(length=32),
               existing_nullable=False,
               existing_server_default=sa.text("'neutral'::text"))
    op.alter_column('users', 'phone',
               existing_type=sa.TEXT(),
               type_=sa.String(length=64),
               existing_nullable=False,
               existing_server_default=sa.text("''::text"))
    op.alter_column('users', 'email',
               existing_type=sa.TEXT(),
               type_=sa.String(length=128),
               existing_nullable=False,
               existing_server_default=sa.text("''::text"))
    op.create_index(op.f('ix_users_manager_user_id'), 'users', ['manager_user_id'], unique=False)
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_manager_user_id'), table_name='users')
    op.alter_column('users', 'email',
               existing_type=sa.String(length=128),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text("''::text"))
    op.alter_column('users', 'phone',
               existing_type=sa.String(length=64),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text("''::text"))
    op.alter_column('tag_dictionaries', 'style_key',
               existing_type=sa.String(length=32),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text("'neutral'::text"))
    op.alter_column('tag_dictionaries', 'field_label',
               existing_type=sa.String(length=128),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text("''::text"))
    op.alter_column('tag_dictionaries', 'field_key',
               existing_type=sa.String(length=64),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text("''::text"))
    op.alter_column('tag_dictionaries', 'object_type',
               existing_type=sa.String(length=32),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text("'candidate'::text"))
    op.drop_constraint(None, 'salary_records', type_='foreignkey')
    op.alter_column('salary_records', 'operator',
               existing_type=sa.String(length=64),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text("''::text"))
    op.alter_column('salary_records', 'candidate_accepted',
               existing_type=sa.String(length=32),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text("''::text"))
    op.alter_column('salary_records', 'agreed_salary',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text("''::text"))
    op.alter_column('salary_records', 'company_name',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text("''::text"))
    op.alter_column('salary_records', 'position_name',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text("''::text"))
    op.alter_column('salary_records', 'interview_round',
               existing_type=sa.String(length=64),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text("''::text"))
    op.drop_index(op.f('ix_projects_owner_user_id'), table_name='projects')
    op.drop_index(op.f('ix_positions_owner_user_id'), table_name='positions')
    op.drop_column('positions', 'target_resume_count')
    op.drop_column('positions', 'requirement_tags')
    op.alter_column('export_records', 'headhunter_position',
               existing_type=sa.String(length=128),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text("''::text"))
    op.alter_column('export_records', 'project_no',
               existing_type=sa.String(length=128),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text("''::text"))
    op.alter_column('export_records', 'contract_no',
               existing_type=sa.String(length=128),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text("''::text"))
    op.drop_index(op.f('ix_companies_owner_user_id'), table_name='companies')
    op.drop_index(op.f('ix_candidates_owner_user_id'), table_name='candidates')
    op.alter_column('candidates', 'file_path',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("''::text"))
    op.alter_column('candidate_tracking_events', 'employment_status',
               existing_type=sa.String(length=32),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text("'待设置'::text"))
    op.alter_column('candidate_tracking_events', 'interview_result',
               existing_type=sa.String(length=32),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text("'-'::text"))
    op.alter_column('candidate_tracking_events', 'interview_contact',
               existing_type=sa.String(length=128),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text("''::text"))
    op.alter_column('candidate_tracking_events', 'interview_location',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text("''::text"))
    op.alter_column('candidate_tracking_events', 'interviewer',
               existing_type=sa.String(length=64),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text("''::text"))
    op.alter_column('candidate_tracking_events', 'interview_date',
               existing_type=sa.String(length=32),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text("''::text"))
    op.alter_column('candidate_tracking_events', 'screening_result',
               existing_type=sa.String(length=32),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text("''::text"))
    op.alter_column('candidate_tracking_events', 'interview_round',
               existing_type=sa.String(length=32),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text("''::text"))
    op.alter_column('ai_tasks', 'created_by',
               existing_type=sa.String(length=64),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text("''::text"))
    # ### end Alembic commands ###
