"""Add ResumeParseTask

Revision ID: 99731a6b4d23
Revises: 0003_enhancement_modules
Create Date: 2026-06-22 22:49:23.289225

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '99731a6b4d23'
down_revision: Union[str, None] = '0003_enhancement_modules'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('candidates', 'birth_date',
               existing_type=sa.TEXT(),
               type_=sa.String(length=64),
               existing_nullable=False,
               existing_server_default=sa.text("''::text"))
    op.alter_column('candidates', 'hukou_location',
               existing_type=sa.TEXT(),
               type_=sa.String(length=128),
               existing_nullable=False,
               existing_server_default=sa.text("''::text"))
    op.alter_column('candidates', 'onboard_cycle',
               existing_type=sa.TEXT(),
               type_=sa.String(length=64),
               existing_nullable=False,
               existing_server_default=sa.text("''::text"))
    op.alter_column('candidates', 'job_status',
               existing_type=sa.TEXT(),
               type_=sa.String(length=64),
               existing_nullable=False,
               existing_server_default=sa.text("''::text"))
    op.alter_column('candidates', 'family_status',
               existing_type=sa.TEXT(),
               type_=sa.String(length=128),
               existing_nullable=False,
               existing_server_default=sa.text("''::text"))
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('candidates', 'family_status',
               existing_type=sa.String(length=128),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text("''::text"))
    op.alter_column('candidates', 'job_status',
               existing_type=sa.String(length=64),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text("''::text"))
    op.alter_column('candidates', 'onboard_cycle',
               existing_type=sa.String(length=64),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text("''::text"))
    op.alter_column('candidates', 'hukou_location',
               existing_type=sa.String(length=128),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text("''::text"))
    op.alter_column('candidates', 'birth_date',
               existing_type=sa.String(length=64),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text("''::text"))
    # ### end Alembic commands ###
